mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://rm-wz9v6ey1y446me9055o.mysql.rds.aliyuncs.com/cinema?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "@qwe123456"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-module
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20889
      accepts: 10
ftp:
  host-name: 10.21.216.203
  port: 2100
  user-name: ftp
  password: ftp
logging:
  level:
    club:
      lightingsummer:
        movie:
          order:
            dal:
              dao: debug
